server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Enable SPA support by falling back to index.html for unknown routes
        try_files $uri $uri/ /index.html;
    }

    # Enable Gzip compression for static files
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}
